<nnb:define "main" "main" "">
  <nnb:button about	"About"		"index.html"	       large>
  <nnb:button screen	"Screenshots"	"screen.html"	       large>
  <nnb:button gallery	"Gallery"	"gallery/"	       large>
  <nnb:button license	"License"	"license.html"	       large>
  <nnb:button download  "Download"	"download.html"	       large>
  <nnb:button compiling "Compiling"	"compiling.html"       large>
  <nnb:button mailinglists "Mailinglists" "mailinglists.html"  large>
  <nnb:button tutorial  "Tutorial"	"tutorial/"	       large>
  <nnb:button manual    "RRDtool Manual" "manual/index.html"   large>
  <nnb:button rrdcgi    "RRDcgi Manual" "rrdcgi.html"    large>
  <nnb:button perlbind  "Perl Bindings"	"perlbind/index.html"  large>
  <nnb:button frontends "Frontends"	"frontends/index.html" large>
  <nnb:button developers "Developers"	"developers.html"      large>
  <nnb:button contrib   "Contributors"  "contributors.html"    large>
</nnb:define>

<nnb:define "sub" manual "manual/">
  <nnb:button rrdcreate	 "create"      rrdcreate.html		small>
  <nnb:button rrdupdate	 "update"      rrdupdate.html		small>
  <nnb:button rrdgraph	 "graph"       rrdgraph.html		small>
  <nnb:button rrddump	 "dump"	       rrddump.html		small>
  <nnb:button rrdinfo	 "info"	       rrdinfo.html		small>
  <nnb:button rrdrestore "restore"     rrdrestore.html		small>
  <nnb:button rrdfetch   "fetch"       rrdfetch.html		small>
  <nnb:button rrdresize	 "resize"      rrdresize.html		small>
  <nnb:button rrdtune	 "tune"	       rrdtune.html		small>
  <nnb:button rrdlast	 "last"	       rrdlast.html		small>
</nnb:define>

<nnb:define "sub" gallery "gallery/">
  <nnb:button alex-01	 "Billing Check"   alex-01.html		small>
  <nnb:button bkw-01	 "Portmaster"   bkw-01.html		small>
  <nnb:button blair-01	 "Webserver"   blair-01.html		small>
  <nnb:button chris-01    "Weather Stats"  chris-01.html		small>
  <nnb:button colleen-01 "Space Shuttle"  colleen-01.html		small>
  <nnb:button edvard-01	 "Link Status"  edvard-01.html		small>
  <nnb:button jeff-01	 "Routing"  jeff-01.html		small>
  <nnb:button neal-01	 "Data Management"  neal-01.html		small>
  <nnb:button steve-01	 "DNS Query Rate"  steve-01.html		small>
  <nnb:button simon-01	 "FluxScope"  simon-01.html		small>
</nnb:define>

<nnb:define "sub" perlbind "perlbind/">
  <nnb:button RRDp	 "RRD Pipes"   RRDp.html		small>
  <nnb:button RRDs	 "Shared RRD"  RRDs.html		small>
</nnb:define>

<nnb:define "sub" tutorial "tutorial/">
  <nnb:button rrdtut	 "First Steps"   rrdtutorial.html		small>
  <nnb:button rpntut	 "RPN Tutorial"  rpntutorial.html		small>
  <nnb:button cdeftut	 "CDEF Tutorial"  cdeftutorial.html		small>
</nnb:define>

<nnb:define "sub" frontends "frontends/">
  <nnb:button bigsister     "BigSister"	   bigsister.html small>
  <nnb:button bronc	    "Bronc"	   bronc.html small>
  <nnb:button cricket	    "Cricket"	   cricket.html small>
  <nnb:button flowscan	    "FlowScan"	   flowscan.html small>  
  <nnb:button fwgold	    "FwGold"	   fwgold.html small>  
  <nnb:button hoth	    "Hoth"	   hoth.html small>  
  <nnb:button nmis          "NMIS"         nmis.html small>
  <nnb:button ntop          "Ntop"         ntop.html small>
  <nnb:button nrg	    "NRG"	   nrg.html small>
  <nnb:button orca	    "Orca"         orca.html small>
  <nnb:button remstats	    "Remstat"	   remstats.html small>
  <nnb:button rrgrapher     "RRGrapher"    rrgrapher.html small>
  <nnb:button slamon        "SLAMon"       slamon.html small>
</nnb:define>
