<nav:bar 0     main "">
 <nav:but welcome        "Welcome"                 index                         />
 <nav:but doc            "Documentation"           doc/index 	       doc       />
 <nav:but tut            "Tutorials"               tut/index           tut       />
 <nav:but prog           "Programming"             prog/index          prog      />
 <nav:but down           "Download"                down                          />
 <nav:but sup            "Support"                 sup                           />
 <nav:but cast           "Cast" 	           cast                          />
</nav:bar>

<nav:bar 1 doc           "doc/">
#include "doc/navbar.inc"
</nav:bar>

<nav:bar 1 tut           "tut/">
#include "tut/navbar.inc"
</nav:bar>

<nav:bar 1 prog           "prog/">
#include "prog/navbar.inc"
</nav:bar>

# <nav:bar 1 probe        "probe/">
# #include "probe/navbar.inc"
# </nav:bar>

# <nav:bar 1 matcher      "matcher/">
# #include "matcher/navbar.inc"
# </nav:bar>

# <nav:bar 1 lib		"lib/">
# #include "lib/navbar.inc"
# </nav:bar>
