<nav:bar 0     main "">
 <nav:but welcome        "Welcome"                 index                         />
 <nav:but down           "Download"                down                          />
 <nav:but license        "License"                 license                       />
 <nav:but doc            "Documentation"           doc/index 	       doc       />
 <nav:but tut            "Tutorials"               tut/index           tut       />
 <nav:but support        "Support"                 support                       />
 <nav:but sponsor        "Sponsorship"             sponsor                       />
# <nav:but gallery        "Gallery"                 gallery/index       gallery   />
# <nav:but rrdworld       "RRDworld"                rrdworld/index      rrdworld  />
 <nav:but prog           "Programming"             prog/index          prog      />
 <nav:but cast           "Cast" 	           cast                          />
</nav:bar>

<nav:bar 1 doc           "doc/">
#include "doc/navbar.inc"
</nav:bar>

<nav:bar 1 tut           "tut/">
#include "tut/navbar.inc"
</nav:bar>

<nav:bar 1 prog           "prog/">
#include "prog/navbar.inc"
</nav:bar>

<nav:bar 1 gallery         "gallery/">
#include "gallery/navbar.inc"
</nav:bar>

<nav:bar 1 rrdworld         "rrdworld/">
#include "rrdworld/navbar.inc"
</nav:bar>

